packages:
  - name: olkyl
    actions:
      - name: getStatus
        limits:
          timeout: 10000
          memory: 256
      - name: checkFridgeStatus
        limits:
          timeout: 10000
          memory: 256
      - name: handleFridgeAction
        limits:
          timeout: 20000
          memory: 256
environment:
  SLACK_TOKEN: ${SLACK_TOKEN}
  SHELLY_URL: ${SHELLY_URL}
  DEVICE_ID: ${DEVICE_ID}
  SHELLY_KEY: ${SHELLY_KEY}
  SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
